name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Web Unit tests
        run: docker compose run unittest
      - name: Clean up after unittest
        run: docker compose down --remove-orphans --volumes

  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            devabdullahq/flask-app-ci:latest
            devabdullahq/flask-app-ci:${{ github.sha }}
          cache-from: type=registry,ref=devabdullahq/flask-app-ci:latest
          cache-to: type=inline
      - name: Run Docker Compose
        run: docker compose up -d
